services:
  spark-master:
    image: apache/spark:4.1.1-scala2.13-java21-python3-r-ubuntu
    container_name: spark-master
    volumes:
      - ./notebooks:/notebooks
    ports:
      - "8080:8080"
      - "7077:7077"
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
  
  spark-worker:
    image: apache/spark:4.1.1-scala2.13-java21-python3-r-ubuntu
    volumes:
      - ./notebooks:/notebooks
    environment:
      SPARK_MASTER_URL: spark://spark-master:7077
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    depends_on:
      - spark-master
  
  jupyter:
    build:
      context: ./jupyter
    container_name: spark-jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/notebooks
    environment:
      SPARK_MASTER: spark://spark-master:7077
    depends_on:
      - spark-master
      - spark-worker